# Generated by Django 5.2.3 on 2025-06-27 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_remove_exam_course_exam_subject'),
        ('users', '0003_examinationtype_alter_user_examination_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='examination_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.examinationtype'),
        ),
        migrations.AddField(
            model_name='exam',
            name='year',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
