# Generated by Django 5.2.3 on 2025-06-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='passing_score',
            field=models.IntegerField(default=70),
        ),
    ]
