# Generated by Django 5.2.3 on 2025-06-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_assignment_assignmentquestion_assignmentchoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentchoice',
            name='choice_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
